[build]
  publish = "."

[context.production.environment]
  IDENTITY_REDIRECT_URL = "https://urserwis.netlify.app/admin/#/recover"
  IDENTITY_CONFIRMATION_REDIRECT_URL = "https://urserwis.netlify.app/admin/#/confirm"
