[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[context.production.environment]
  IDENTITY_REDIRECT_URL = "/admin/"
  IDENTITY_CONFIRMATION_REDIRECT_URL = "/admin/"
